config/routes.rb
Rails.application.routes.draw do
  resources :games
  get  'play/:id', to: 'games#play'
  get  'start/:id', to: 'games#start'
  get  'hint/:id', to:'games#hint'
  get  'discover/:id', to:'games#discover'
  get  'history/:id', to:'games#history'

  get 'nearby', to:'locations#nearby'

  get 'password_resets/new'

  get 'password_resets/edit'

  resources :locations
  get 'sessions/new'

  root 'home_pages#home'
  get  '/about',   to: 'home_pages#about'
  resources :users

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :password_resets,     only: [:new, :create, :edit, :update]

  match	':controller(/:action(/:id))',	:via	=>	:get

end

app/models/game.rb
class Game < ActiveRecord::Base
  # add the accessors for the two fields
  belongs_to :organizer, class_name: "User", foreign_key: "organizer_id"

  has_many :hunts, dependent: :delete_all
  has_many :locations, through: :hunts

  has_many :plays, dependent: :delete_all
  has_many :users, through: :plays

  has_many :game_histories, dependent: :destroy

  reverse_geocoded_by :latitude, :longitude, :address => :address

  validates :title, presence: true, length: { maximum: 64 }
  validates :duration, presence: true, numericality: { greater_than_or_equal_to: 5, less_than_or_equal_to: 120}
  validates :starts_at_time, presence: true
  validates :starts_at_date, presence: true
  validates :latitude, presence: true, numericality: true
  validates :longitude, presence: true, numericality: true
  validates :locations, presence: true

  after_validation :reverse_geocode  # auto-fetch address


end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  include GamesHelper
  before_action :set_game, only: [:show, :edit, :update, :destroy, :play]

  #Only allow joined users to play game
  before_action :is_joined, only: [:play, :start, :hint, :discover, :history]

  # GET /games
  def index
    @games = Game.all
  end

  # GET /games/1
  def show
  end

  # GET /games/new
  def new
    @locations = Location.all
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  def create
    @game = Game.new(game_params)
    @game.organizer = current_user
    if @game.save
      flash[:success] = 'Game was successfully created.'
      redirect_to @game
    else
      render :new
    end
  end

  # PATCH/PUT /games/1
  def update
    if @game.update(game_params)
      flash[:success] = 'Game was successfully updated.'
      redirect_to @game
    else
      render :edit
    end
  end

  # DELETE /games/1
  def destroy
    Game.find(params[:id]).destroy
    flash[:success] = 'Game was successfully destroyed.'
    redirect_to games_url
  end

  # GET /games/play/1
  def play
    @game_start_datetime = get_game_start_datetime(params[:id])
    @game_end_datetime = get_game_end_datetime(params[:id])
    user_game_history = GameHistory.where(:user_id => current_user.id, :game_id => params[:id])
    @has_history =  user_game_history.count == @game.locations.all.count
    @found_all = !GameHistory.exists?(user_id:current_user.id, game_id:params[:id], discovered:false)
    @players_info = Play.where(game_id:params[:id]).order(points: :desc)
    @locations_history = {}
    user_game_history.each do |his|
      @locations_history[his.location_id] = { 'discovered': his.discovered,
        'hint1_used': his.hint1_used, 'hint2_used': his.hint2_used}
    end
  end

  # GET /games/start/1
  def start
    game_id = params[:id]
    game = Game.find(game_id)
    if is_active_game(game_id)
      game.locations.all.each do |loc|
        GameHistory.create(user_id:current_user.id, game_id:game_id,
                           location_id:loc.id, discovered:false,
                           hint1_used:false, hint2_used:false)

      end
    else
      flash[:danger] = 'Game cannot start, please makes sure you are playing the game at the correct time'
    end
    redirect_to controller: 'games', action: 'play', id:game_id
  end

  # GET /games/hint/1
  def hint
    game_id = params[:id]
    location_id = params[:lid]
    hint_number = params[:hnum]
    game = Game.find(game_id)
    if is_active_game(game_id)
      game_history = GameHistory.find_by(user_id:current_user.id,
                                         game_id:game_id, location_id:location_id)
      user_play = Play.find_by(user_id:current_user.id, game_id:game_id)
      location = Location.find(location_id)
      if hint_number == '1'
        game_history.hint1_used = true;
        game_history.save

        hint1_points = location.hint1_points
        hint = location.hint1
        user_play.points = user_play.points - hint1_points
        user_play.save
      elsif hint_number == '2'
        game_history.hint2_used = true;
        game_history.save

        hint2_points = location.hint2_points
        hint = location.hint2
        user_play.points = user_play.points - hint2_points
        user_play.save
      end
      render json: {message:'Hint Used', hint: hint}, status: 200
    else
      render json: {message:'Could not use hint, please makes sure you are playing the game at the correct time.'}, status: 400
    end
  end

  # GET /games/discover/1
  def discover
    game_id = params[:id]
    location_id = params[:lid]
    lat = Float(params[:lat])
    lng = Float(params[:lng])
    game = Game.find(game_id)
    if is_active_game(game_id)
      game_history = GameHistory.find_by(user_id:current_user.id,
                                         game_id:game_id, location_id:location_id)
      user_play = Play.find_by(user_id:current_user.id, game_id:game_id)
      location = Location.find(location_id)
      distance = location.distance_from([lat,lng])
      if distance <= 0.003
        game_history.discovered = true;
        game_history.save

        points = location.points
        user_play.points = user_play.points + points
        user_play.save
        if !GameHistory.exists?(user_id:current_user.id, game_id:game_id, discovered:false)
          # add points for first 3 players
          finished_players = Play.where(game_id:game_id).where.not(finish_time: nil)
          user_play.rank = finished_players.count + 1
          if finished_players.count <= 2
            user_play.points = user_play.points + ((finished_players.count - 3) * -2)
          end
          user_play.finish_time = DateTime.now
          user_play.save
        end
        render json: {message:'Location Found!'}, status: 200
      else
        render json: {message:'Unsuccessful Dicovery, try again.'}, status: 400
      end
    else
      render json: {message:'Could not find location, please makes sure you are playing the game at the correct time.'}, status: 400
    end
  end

  # GET /games/history/1
  def history
    game_id = params[:id]
    @game = Game.find(game_id)
    @game_start_datetime = get_game_start_datetime(game_id)
    @user_game_history = GameHistory.where(user_id:current_user.id, game_id:game_id)
    @found_all = !GameHistory.exists?(user_id:current_user.id, game_id:game_id, discovered:false)
    @user_play = Play.find_by(user_id:current_user.id, game_id:game_id)
    @players_info = Play.where(game_id:game_id).order(points: :desc)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    def is_joined
      if (logged_in? && Play.find_by(:user_id => current_user.id, :game_id => params[:id]))
        return true
      end
      redirect_to games_url
    end

    def is_active_game(game_id)
      game = Game.find(game_id)
      game_start_datetime = get_game_start_datetime(game_id)
      game_end_datetime = get_game_end_datetime(game_id)
      if game_start_datetime <= DateTime.now && game_end_datetime >= DateTime.now
        return true
      else
        return false
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params[:game].permit(:title,:duration,:starts_at_date,:starts_at_time,:latitude,:longitude, location_ids: [])
    end
end

app/helpers/games_helper.rb
module GamesHelper
  def get_game_start_datetime(gid)
    game = Game.find(gid)
    start_dt = Time.zone.local(game.starts_at_date.year,
                            game.starts_at_date.month,
                            game.starts_at_date.day,
                            game.starts_at_time.hour,
                            game.starts_at_time.min,
                            game.starts_at_time.sec)
    return start_dt
  end

  def get_game_end_datetime(gid)
    game = Game.find(gid)
    start_dt = get_game_start_datetime(gid)
    end_dt = start_dt + game.duration.minutes
    return end_dt
  end
end

app/views/games/_form.html.erb
<div class="row panel-body">
<%= bootstrap_form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@game.errors.count, "error") %>
      </div>
      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-6">
    <%= f.text_field :title %>
    <%= f.number_field :duration, append: "min"%>
    <%= f.text_field :starts_at_date, class: 'datepicker', label: 'Start Date' %>
    <%= f.time_select :starts_at_time, label: 'Start Time' %>
  </div>
  <div class="col-md-6">
    <%= f.hidden_field :latitude %>
    <%= f.hidden_field :longitude %>
    <div class="form-group">
      <label class="control-label">Starting Point</label>
      <%= render 'map' %>
    </div>
  </div>
  <div class="col-md-12" id="game-locations">
    <div class="row">
      <div class="form-group col-md-6">
        <label class="control-label" for="distance">Filter locations by distance from starting point:</label>
        <div class="input-group">
          <input class="form-control" value=2 type="number" name="distance" id="distance">
          <span class="input-group-addon">km</span>
        </div>
      </div>
    </div>
    <div class="row">
        <% Location.all.each do |location| %>
        <div class="col-md-3">
          <div class="form-group js-gm-loc" id="l<%= location.id %>">
            <%= image_tag location.image.url(:square) %>
            <div class="checkbox">
              <label>
                <%= check_box_tag "game[location_ids][]", location.id, f.object.locations.include?(location)%>
                <%= location.area %> Area
              </label>
            </div>
          </div>
        </div>
        <% end %>
    </div>
  </div>
  <div class="col-md-12">
    <%= f.button "Submit", type: 'submit', class: 'btn btn-primary' %>
    <%= link_to 'Back', games_path, class: 'btn btn-warning' %>
  </div>
<% end %>
</div>

app/views/games/_map.html.erb
<div id="map" style="height:300px;"></div>

<script async defer
  src="https://maps.googleapis.com/maps/api/js?key=<%= Rails.configuration.google_api_key %>&callback=initGameMap">
</script>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

app/views/games/history.html.erb
<h2> <%= @game.title %> History</h2
<!-- Game not started yet -->
<% if @game_start_datetime > DateTime.now %>
  <div class="row">
    <div class="col-md-12">
      <p>
        This game has not started yet. Please check again at
        <b><%= @game_start_datetime.strftime("%F @ %H:%M:%S") %></b>
      </p>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col-md-8">
      <h3> Your Game Stats </h3>
      <table id="js-histoty-dt" class="table table-condensed table-striped table-bordered">
        <thead>
          <tr>
            <th>location</th>
            <th>Hint 1 Used</th>
            <th>Hint 2 Used</th>
            <th>Final Point</th
          </tr>
        </thead>
        <tbody>
          <% @user_game_history.each do |history| %>
            <% @location = Location.find(history.location_id) %>
            <% @point_count = 0 %>
            <tr>
              <td>
                <div class="wrapper">
                  <%= image_tag @location.image.url(:thumb) %>
                  <% if history.discovered %>
                    <% @point_count = @location.points %>
                    <span class="glyphicon glyphicon-ok js-location-choice"></span>
                  <% end %>
                </div>
              </td>
              <td>
                <% if history.hint1_used%>
                  Yes: -<%=@location.hint1_points %> point(s)
                  <% @point_count = @point_count - @location.hint1_points %>
                <% else %>
                  No
                <% end %>
              </td>
              <td>
                <% if history.hint2_used%>
                  Yes -<%=@location.hint2_points %> points(s)
                  <% @point_count = @point_count - @location.hint2_points %>
                <% else %>
                  No
                <% end %>
              </td>
              <td>
                <%=@point_count %>
              </td>
            </tr>
          <% end %>
          <tr>
            <td colspan="3">
              Top 3 Finish bonus:
              <% if @user_play.rank && @user_play.rank <= 3%>
                <%= (@user_play.rank - 4) * -2 %>
              <% else %>
                0
              <% end %>
            </td>
            <td colspan="1">
              Total: <%= @user_play.points %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col-md-4">
      <h3> Players Stats </h3>
      <table id="js-player-dt" class="table table-condensed table-striped table-bordered">
        <thead>
          <tr>
            <th>Player</th>
            <th>Points</th>
            <th>Finished</th>
          </tr>
        </thead>
        <tbody>
          <% @players_info.each do |play| %>
            <tr>
              <td><%= User.find(play.user_id).username %></td>
              <td><%= play.points %></td>
              <td>
                <% if play.finish_time==nil %>
                  No
                <% else %>
                  Yes
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>

app/views/games/index.html.erb
<% provide(:title, 'All games') %>
<h2>Listing Games</h2>

<div class="row">
  <table id="js-games-dt" class="table table-condensed table-striped table-bordered">
    <thead>
    <tr>
      <th>Game name</th>
      <th>Game address</th>
      <th>Start date</th>
      <th>Start time</th>
      <th>Duration(min)</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>

    <!-- if the game is passed and the user is regular user, the passed game is hided  -->
    <% if  logged_in? && get_game_end_datetime(game.id) < DateTime.now && !(current_user.is_admin?) %>

    <% else %>

      <tr>
        <td><%= game.title %></td>
        <td><%= game.address %></td>
        <td><%= game.starts_at_date %></td>
        <td><%= game.starts_at_time.strftime("%H:%M:%S") %></td>
        <td><%= game.duration %></td>
        <td>
          <% if logged_in? && current_user.is_admin?  %>
            <%= link_to 'Show', game, class: 'btn btn-info' %>
              <%= link_to 'Edit', edit_game_path(game), class: 'btn btn-info' %>
              <%= link_to 'Delete', game, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>


           <!--if the admin is not the game organizer, then he can join or leave the game -->

           <% if current_user.id != game.organizer_id && get_game_start_datetime(game.id) > DateTime.now%>
             <% if (Play.find_by(:user_id => current_user.id, :game_id => game.id))%>
             <%= link_to "leave Game", user_path(current_user, :gid => game.id, :leave => game.id), class: "btn btn-danger" %>

             <% else %>
             <%= link_to "Join Game", user_path(current_user, :gid => game.id), class: "btn btn-success" %>
             <% end %>
           <% end %>




          <!--if the user is not admin, if the game is passed, don't show the game. also
        need to determine if the user is organizer -->
          <% else %>
            <!-- if the user is organizer and the game is not passed
          the user can see show  edit and delete page-->

            <% if logged_in? && get_game_start_datetime(game.id) > DateTime.now && current_user.id == game.organizer_id %>
              <%= link_to 'Show', game, class: 'btn btn-info' %>
              <%= link_to 'Edit', edit_game_path(game), class: 'btn btn-info' %>
              <%= link_to 'Delete', game, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
              <!-- elsif the user is game organizer and the game is not passed, the user
              can see the game show page -->
            <% elsif logged_in? && get_game_end_datetime(game.id) > DateTime.now && current_user.id == game.organizer_id %>
              <%= link_to 'Show', game, class: 'btn btn-info' %>
              <!-- elsif the user is not game organizer and the game is not passed, the user
          can see the game show page and join or leave the game page  -->
              <% elsif logged_in? && get_game_end_datetime(game.id) > DateTime.now && current_user.id != game.organizer_id %>
                <%= link_to 'Show', game, class: 'btn btn-info' %>
                <% if (Play.find_by(:user_id => current_user.id, :game_id => game.id))%>
              <%= link_to "leave Game", user_path(current_user, :gid => game.id, :leave => game.id), class: "btn btn-danger" %>

                <% else %>
                  <%= link_to "Join Game", user_path(current_user, :gid => game.id), class: "btn btn-success" %>
                <% end %>
              <!-- else the user is not organizer and the game is passed, the user can see nothing -->
              <% else %>
              <% end %>
       <% end %>

        </td>
      </tr>

    <% end %>
  <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New Game', new_game_path, class: 'btn btn-primary' %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

app/views/games/play.html.erb
<!-- Game not started yet -->
<% if @game_start_datetime > DateTime.now %>
  <div class="row">
    <div class="col-md-6">
    <h2> <%= @game.title %> </h2>
    <p>
      This game has not started yet. Please check again at
      <b><%= @game_start_datetime.strftime("%F @ %H:%M:%S") %></b>
    </p>
  </div>
    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-body">
          <div id="start-clock"></div>
        </div>
      </div>
    </div>
  </div>

<!-- Game ended-->
<% elsif @game_end_datetime < DateTime.now %>
  <div class="row">
    <div class="col-md-12">
      <h2> <%= @game.title %> </h2>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <p>
        This game has ended. Click more games to check future games. <br/>
        <%= link_to 'More Games', games_path, class:"btn btn-primary show-grid " %></b>
      </p>
    </div>
    <div class="col-md-6">
      <div class="panel panel-default" style="border-color:crimson; color: crimson;">
        <div class="panel-body">
          <div id="game-clock"></div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <h3> Players Stats </h3>
      <table id="js-player-dt" class="table table-condensed table-striped table-bordered">
        <thead>
          <tr>
            <th>Player</th>
            <th>Points</th>
            <th>Finished</th>
          </tr>
        </thead>
        <tbody>
          <% @players_info.each do |play| %>
            <tr>
              <td><%= User.find(play.user_id).username %></td>
              <td><%= play.points %></td>
              <td>
                <% if play.finish_time==nil %>
                  No
                <% else %>
                  Yes
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

<!-- Game ready to play-->
<% else%>
  <div class="row">
    <div class="col-md-6">
      <h2>
        <%= @game.title %>
        <% if @has_history %>
          <% if @found_all %>
            <span style="color:green">(You are Done!)</span>
          <% else %>
            <span style="color:deepskyblue">(Playing...)</span>
          <% end %>

        <% else %>
          <a href="/games/start/<%=@game.id%>" data-gameid="<%=@game.id%>" class="btn btn-primary">
            <span class="glyphicon glyphicon-play-circle" aria-hidden="true"></span> Start
          </a>
        <% end %>
      </h2>
    </div>
    <div class="col-md-6">
      <div class="panel panel-default">
        <div class="panel-body">
          <div id="game-clock"></div>
        </div>
      </div>
    </div>
  </div>

  <div class="row show-grid highlight">
    <% @game.locations.all.each do |location| %>
    <div class="col-sm-2">
      <div class="wrapper">
        <%= image_tag location.image.url(:thumb), data: {locationid:location.id},  class:"js-location-choice"%>
        <% if @has_history && @locations_history[location.id][:discovered]%>
          <span class="glyphicon glyphicon-ok js-location-choice" data-locationid="<%=location.id%>"></span>
        <% end %>
      </div>
    </div>
    <% end %>
  </div>
  <% if @has_history %>
    <div id="js-play-locations">
      <div class="row show-grid highlight">
        <% @game.locations.all.each do |location| %>
          <div class="js-location" id="js-location-<%=location.id %>">
            <div class="col-md-6">
              <%= image_tag location.image.url(:medium) %>
            </div>
            <div class="col-md-6">
              <div class="row show-grid">
                <div class="col-md-12 show-grid">
                  <%=location.description %> <b>(<%=location.points %> point(s))</b>
                </div>
                <% if !@locations_history[location.id][:discovered]%>
                  <div class="col-md-12 show-grid">
                    <% if @locations_history[location.id][:hint1_used]%>
                      <span id="js-hint1-<%=location.id %>"><b>Hint 1:</b> <%= location.hint1%></span>
                    <% else %>
                      <button type="button" data-hint=1 data-gameid="<%=@game.id%>"  data-locationid="<%=location.id %>"class="btn btn-info js-hint">
                        <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span> Use Hint
                      </button>
                      <span id="js-hint1-<%=location.id %>"> Using this hint costs <%= location.hint1_points%> point(s)</span>
                    <% end %>
                  </div>
                  <div class="col-md-12 show-grid">
                    <% if @locations_history[location.id][:hint2_used]%>
                      <span id="js-hint2-<%=location.id %>"><b>Hint 2:</b> <%= location.hint2%></span>
                    <% else %>
                      <button type="button" data-hint=2 data-gameid="<%=@game.id%>" data-locationid="<%=location.id %>" class="btn btn-info js-hint">
                        <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span> Use Hint
                      </button>
                      <span id="js-hint2-<%=location.id %>"> Using this hint costs <%= location.hint2_points%> point(s)</span>
                    <% end %>
                  </div>
                <% end %>
                <div class="col-md-12 show-grid">
                  <% if @locations_history[location.id][:discovered]%>
                    <b> Already Discovered! </b>
                  <% else %>
                    <button class="js-location-found btn btn-success btn-lg" type="button" data-gameid="<%=@game.id%>" data-locationid="<%=location.id %>" style="width:100%;"> Found It!
                    </button>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>

<% end %>
<script>
$('#start-clock').countdown({
  until:new Date("<%=@game_start_datetime.utc.strftime("%FT%H:%M:%S")%>"),
  format: 'MS',
  onExpiry: function() {
    location.reload();
  }
})
$('#game-clock').countdown({
  until:new Date("<%=@game_end_datetime.utc.strftime("%FT%H:%M:%S")%>"),
  format: 'MS',
  onExpiry: function() {
    location.reload();
  }
})
</script>

app/views/games/show.html.erb
<div class="game-show text-center">
  <div class="container-fluid text-center">
    <h2>Information</h2>
    <h4>--Game--</h4>
    <br>
    <img class="google-static-map" src="https://maps.googleapis.com/maps/api/staticmap?center=<%= @game.latitude %>, <%= @game.longitude %>&zoom=14&size=600x400&maptype=roadmap&markers=color:red%7C<%= @game.latitude %>, <%= @game.longitude %>&key=<%= Rails.configuration.google_api_key %>">
    <br>
    <br>
    <div class="row" >
      <div class="col-sm-4">
        <span class="glyphicon glyphicon-certificate"></span>
        <h4>TITLE</h4>
        <p><%= @game.title %></p>
      </div>
      <div class="col-sm-4">
        <span class="glyphicon glyphicon-time"></span>
        <h4>START DATE</h4>
        <p><%= @game.starts_at_date %></p>
      </div>
      <div class="col-sm-4">
        <span class="glyphicon glyphicon-time"></span>
        <h4>START TIME</h4>
        <p><%= @game.starts_at_time.strftime("%H:%M:%S") %></p>
      </div>
      </div>
    <br><br>
    <div class="row">
      <div class="col-sm-4">
        <span class="glyphicon glyphicon-map-marker"></span>
        <h4>ADDRESS</h4>
        <p><%= @game.address %></p>
      </div>
      <div class="col-sm-4">
        <span class="glyphicon glyphicon-leaf"></span>
        <h4>DURATION</h4>
        <p><%= @game.duration %> minutes</p>
      </div>
      <div class="col-sm-4">
        <span class="glyphicon glyphicon-globe"></span>
        <h4>ORGANIZER</h4>
        <% if @game.organizer.present? %>
        <p>
          <%= @game.organizer.username %>
        </p>
      <% end %>
      </div>
    </div>

    <br>
    <br>
    <% if @game.organizer_id != current_user.id && get_game_start_datetime(@game.id) > DateTime.now%>
      <% if (Play.find_by(:user_id => current_user.id, :game_id => @game.id))%>
        <%= link_to "leave Game", user_path(current_user, :gid => @game.id, :leave => @game.id), class: "btn btn-danger" %>

      <% else %>
        <%= link_to "Join Game", user_path(current_user, :gid => @game.id), class: "btn btn-success" %>
      <% end %>
    <% end %>


  </div>
  <br>
  <div lass="button-game-show">
    <% if logged_in? && current_user.is_admin? %>
      <%= link_to 'Edit', edit_game_path(@game), class: 'btn btn-info' %> |
    <% elsif  logged_in? && current_user.id == @game.organizer_id && get_game_start_datetime(@game.id) > DateTime.now%>
      <%= link_to 'Edit', edit_game_path(@game), class: 'btn btn-info' %> |
    <% else %>
    <% end %>
    <%= link_to 'Back', games_path, class: 'btn btn-warning' %>

  </div>
</div>