config/routes.rb
Rails.application.routes.draw do
  resources :games
  get  'play/:id', to: 'games#play'
  get  'start/:id', to: 'games#start'
  get  'hint/:id', to:'games#hint'
  get  'discover/:id', to:'games#discover'
  get  'history/:id', to:'games#history'

  get 'nearby', to:'locations#nearby'

  get 'password_resets/new'

  get 'password_resets/edit'

  resources :locations
  get 'sessions/new'

  root 'home_pages#home'
  get  '/about',   to: 'home_pages#about'
  resources :users

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :password_resets,     only: [:new, :create, :edit, :update]

  match	':controller(/:action(/:id))',	:via	=>	:get

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The group project for CMPT 276
  </small>
  <nav>
    <ul>
      <li><%= link_to "Home",   root_path %></li>
      <li><%= link_to "About",   about_path %></li>
      <li><a href="https://courses.cs.sfu.ca/" target="blank">Coursys</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-3">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
    <%= link_to "urban hunt", root_path, id: "logo" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-3">
    <ul class="nav navbar-nav navbar-left">
      <% if logged_in? && current_user.is_admin? %>
      <li><%= link_to "Users", users_path %></li>
      <li><%= link_to "Locations", locations_path %></li>
      <% end %>
    </ul>
    <% if logged_in? %>
      <span id="hello"> Hello <%=current_user.username%>! </span>
    <% end %>

    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home",   root_path %></li>
      <li><%= link_to "About",   about_path %></li>
      <% if logged_in? %>
        <li><%= link_to "Games", games_path %></li>
        <li><%= link_to "Profile", current_user %></li>
        <li><%= link_to "Log out", logout_path, method: "delete" %></li>
      <% else %>
        <li><%= link_to "Log in", login_path %></li>
      <% end %>
    </ul>

  </div><!-- /.navbar-collapse -->
</div><!-- /.container -->
</nav><!-- /.navbar -->

<div class="margin-page">
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= render 'layouts/shim' %>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">

    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <div id="alert-message"></div>

    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>